language: go
go:
  - "1.12"
script:
  - GO111MODULE=on go test -race -cover -count=5 ./...
  - cd $TRAVIS_BUILD_DIR/v3 && GO111MODULE=on go test -race -cover -count=5 ./...
  - cd $TRAVIS_BUILD_DIR/v4 && GO111MODULE=on go test -race -cover -count=5 ./...